---

#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure Glance API
  ini_file:
    dest: /etc/glance/glance-api.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  notify:
    - Restart Glance API
  with_items:
    - section: DEFAULT
      option: rpc_backend
      value: rabbit
    - section: DEFAULT
      option: bind_host
      value: '{{ openstack_glance_bind_host }}'
    - section: DEFAULT
      option: bind_port
      value: '{{ openstack_glance_port }}'
    - section: DEFAULT
      option: rabbit_host
      value: '{{ openstack_glance_rabbit_hostname }}'
    - section: DEFAULT
      option: rabbit_userid
      value: '{{ openstack_glance_rabbit_username }}'
    - section: DEFAULT
      option: rabbit_password
      value: '{{ openstack_glance_rabbit_password }}'
    - section: DEFAULT
      option: rabbit_virtual_host
      value: '{{ openstack_glance_rabbit_virtual_host }}'
    - section: DEFAULT
      option: log_file
      value: '{{ openstack_glance_log_dir }}/api.log'
    - section: DEFAULT
      option: verbose
      value: True
    - section: database
      option: connection
      value: '{{ openstack_glance_database_url }}'
    - section: keystone_authtoken
      option: identity_uri
      value: >-
        {{- openstack_glance_keystone_protocol }}://
        {{- openstack_glance_keystone_hostname }}:
        {{- openstack_glance_keystone_admin_port }}
    - section: keystone_authtoken
      option: auth_url
      value: >-
        {{- openstack_glance_keystone_protocol }}://
        {{- openstack_glance_keystone_hostname }}:
        {{- openstack_glance_keystone_admin_port }}
    - section: keystone_authtoken
      option: auth_uri
      value: >-
        {{- openstack_glance_keystone_protocol }}://
        {{- openstack_glance_keystone_hostname }}:
        {{- openstack_glance_keystone_port }}/v3
    - section: keystone_authtoken
      option: project_domain_name
      value: default
    - section: keystone_authtoken
      option: user_domain_name
      value: default
    - section: keystone_authtoken
      option: memcached_servers
      value: '{{ openstack_glance_keystone_hostname }}:11211'
    - section: keystone_authtoken
      option: admin_tenant_name
      value: service
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: auth_version
      value: v3
    - section: keystone_authtoken
      option: username
      value: '{{ openstack_glance_user }}'
    - section: keystone_authtoken
      option: password
      value: '{{ openstack_glance_pass }}'
    - section: paste_deploy
      option: flavor
      value: keystone

- name: Configure Glance registry
  ini_file:
    dest: /etc/glance/glance-registry.conf
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  notify:
    - Restart Glance registry
  with_items:
    - section: DEFAULT
      option: log_file
      value: '{{ openstack_glance_log_dir }}/registry.log'
    - section: DEFAULT
      option: verbose
      value: True
    - section: database
      option: connection
      value: '{{ openstack_glance_database_url }}'
    - section: keystone_authtoken
      option: identity_uri
      value: >-
        {{- openstack_glance_keystone_protocol }}://
        {{- openstack_glance_keystone_hostname }}:
        {{- openstack_glance_keystone_admin_port }}
    - section: keystone_authtoken
      option: auth_uri
      value: >-
        {{- openstack_glance_keystone_protocol }}://
        {{- openstack_glance_keystone_hostname }}:
        {{- openstack_glance_keystone_port }}/v3
    - section: keystone_authtoken
      option: admin_tenant_name
      value: service
    - section: keystone_authtoken
      option: admin_user
      value: glance
    - section: keystone_authtoken
      option: admin_password
      value: '{{ openstack_glance_pass }}'
    - section: paste_deploy
      option: flavor
      value: keystone
    - section: glance_store
      option: stores
      value: glance.store.filesystem.Store,glance.store.http.Store
    - section: glance_store
      option: filesystem_store_datadir
      value: /var/lib/glance/images/
    - section: glance_store
      option: default_store
      value: file

- name: Get current Glance database version
  command: 'glance-manage db_version'
  always_run: True
  become: True
  become_user: 'glance'
  changed_when: openstack_glance_manage_db_version.stdout|int != openstack_glance_database_schema_version
  register: openstack_glance_manage_db_version

- name: Migrate Glance database to desired version
  command: 'glance-manage db_sync {{ openstack_glance_database_schema_version }}'
  become: True
  become_user: 'glance'
  notify:
    - Restart Glance API
    - Restart Glance registry
  when: openstack_glance_manage_db_version|changed
