# -*- mode: ruby -*-
# vi: set ft=ruby :

######################################################################

def start(config, box, name, extra_provisioners=[])
  config.vm.define name do |node|
    node.vm.box = box
    node.vm.hostname = name

    if not extra_provisioners.empty? then
      for extra_provisioner in extra_provisioners do
        extra_provisioner.call(node)
      end
    end

    node.vm.provision :ansible do |ansible|
      ansible.playbook = "test.yml"
    end
  end
end

def set_hardware(config, provider)
  config.vm.provider provider do |machine|
    machine.memory = 2048
    machine.cpus = 1
  end
end

def install_python_ubuntu(node)
  node.vm.provision :shell,
    inline: "apt-get update && apt-get install -y python"
end

######################################################################

Vagrant.configure(2) do |config|
  set_hardware config, :libvirt
  set_hardware config, :virtualbox

  config.vm.provider :libvirt do |libvirt|
    start config, "iknite/trusty64",   "ubuntu-trusty"
    start config, "yk0/ubuntu-xenial", "ubuntu-xenial", [method(:install_python_ubuntu)]
    start config, "centos/7",          "centos-7"
  end

  config.vm.provider :virtualbox do |libvirt|
    start config, "ubuntu/trusty64", "ubuntu-trusty"
    start config, "ubuntu/xenial64", "ubuntu-xenial", [method(:install_python_ubuntu)]
    start config, "centos/7",        "centos-7"
  end
end
